cloudflare:
  waf:
    default:
      firewall_settings:
        security_level: "high"
        browser_integrity_check: "on"
        automatic_https_rewrites: "on"
      rules:
        - description: "Block bad user agents"
          expression: "(http.user_agent contains \"bad-bot\")"
          action: "block"
    zones:
      - id: "b441db6e139659910adc1155990213e2"
        domain: "freesubnet.com"
        waf:
          firewall_settings:
            security_level: "under_attack"
            browser_integrity_check: "off" #override default
            automatic_https_rewrites: "on" #no override
          rules:
            - description: "Challenge suspicious requests"
              expression: "(ip.geoip.country eq \"RU\")"
              action: "challenge"
