cloudflare:
  waf:
    default:
      firewall_settings:
        security_level: "high"
    zones:
      - id: "b441db6e139659910adc1155990213e2"
        domain: "freesubnet.com"
        waf:
          firewall_settings:
            security_level: "under_attack"
