cloudflare:
  waf:
    default:
      firewall_settings:
        security_level: "high"
    zones:
      - id: "b441db6e139659910adc1155990213e2"  # Your zone ID
        domain: "freesubnet.com"                 # Your domain
        waf:
          firewall_settings:
            security_level: "medium"
